# Homework 4: PCA

In [38]:
import numpy as np

In [39]:
X = np.array([[-2, 1,  4,  6,  5,  3,  6, 2],
              [ 9, 3,  2, -1, -4, -2, -4, 5],
              [ 0, 7, -5,  3,  2, -3,  4, 6]])

## 1. Compute best 1D representation of X

In [40]:
X1 = X - X.mean(axis=1).reshape((3,1)) #centered matrix

In [41]:
X1.mean(axis=1) #should be zero mean

array([0., 0., 0.])

In [42]:
X1

array([[-5.125, -2.125,  0.875,  2.875,  1.875, -0.125,  2.875, -1.125],
       [ 8.   ,  2.   ,  1.   , -2.   , -5.   , -3.   , -5.   ,  4.   ],
       [-1.75 ,  5.25 , -6.75 ,  1.25 ,  0.25 , -4.75 ,  2.25 ,  4.25 ]])

In [43]:
C = X1 @ X1.T #covariance matrix

In [44]:
C

array([[ 52.875, -78.   ,  -1.75 ],
       [-78.   , 148.   ,   6.   ],
       [ -1.75 ,   6.   , 123.5  ]])

In [45]:
eigenvals,eigenvecs = np.linalg.eig(C) #compute eigenvalues and eigenvectors

In [46]:
eigenvals

array([  9.06256536, 192.33362217, 122.97881247])

In [47]:
eigenvecs

array([[-0.87168926, -0.48708504,  0.05390734],
       [-0.48990322,  0.86889736, -0.07079702],
       [ 0.01235577,  0.08812238,  0.99603302]])

In [48]:
pc = eigenvecs[:, np.argmax(eigenvals)] #Get first principal component

In [49]:
pc

array([-0.48708504,  0.86889736,  0.08812238])

In [50]:
W = pc.reshape((3,1))

In [51]:
X1d = W.T @ X #compute best 1d representation of X

In [52]:
X1d

array([[ 8.79424627,  2.73646372, -0.65115735, -3.52704041, -5.73476983,
        -3.46341697, -6.04561009,  3.89905101]])

## 2. PCA Function

In [53]:
def mypca(X, k):
    X1 = X - X.mean(axis=1).reshape((3,1)) #center data matrix
    C = X1 @ X1.T #covariance matrix
    eigenvals,eigenvecs = np.linalg.eig(C) #eigendecomposition
    sort_indices = np.argsort(eigenvals)[::-1] 
    eigenvecs = eigenvecs[:, sort_indices] #sort eigenvecs according to eigenvalues
    pc = eigenvecs[:, :k] #select first k eigenvecs
    pv = eigenvals[sort_indices[:k]] #order and select first k eigenvals
    rep = pc.T @ X # reduce dimensionality of X using first k pc
    return rep, pc, pv

In [54]:
rep, pc1, pv = mypca(X, 2)

In [55]:
rep

array([[ 8.79424627,  2.73646372, -0.65115735, -3.52704041, -5.73476983,
        -3.46341697, -6.04561009,  3.89905101],
       [-0.74498789,  6.81374742, -4.9061298 ,  3.38234013,  2.54479084,
        -2.684783  ,  4.59076422,  5.73002769]])

In [56]:
pc1

array([[-0.48708504,  0.05390734],
       [ 0.86889736, -0.07079702],
       [ 0.08812238,  0.99603302]])

In [57]:
pv

array([192.33362217, 122.97881247])

In [58]:
#import matplotlib.pyplot as plt
#from mpl_toolkits.mplot3d import Axes3D

In [59]:
#fig = plt.figure()
#ax = fig.add_subplot(111, projection='3d')
#ax.scatter(X[0,:], X[1,:], X[2,:])

In [60]:
#plt.scatter(X1d, [1]*8)

In [61]:
#plt.scatter(rep[0,:], rep[1,:])